/* Dataset local. Evita fetch() de JSON para poder abrir las páginas sin servidor. */
const NOTICIAS_BASE = [
  { id: 1, categoria: "Tecnología", titulo: "Anthropic, empresa creadora de Claude, anunció que detectó y desarticuló posibles complots que usaban su IA para investigar sobre armas biológicas", resumen: "Estas declaraciones se dan en medio de diversas advertencias sobre ciberseguridad y el avance de las nuevas tecnologías.", contenido: "El anuncio se produce después de que uno de sus ingenieros alertara del peligro existencial de estas herramientas si no se establecen controles adecuados. Anthropic detalló que reforzará sus sistemas de clasificación de contenido sensible y ampliará el equipo dedicado a la seguridad de sus modelos, en línea con los compromisos asumidos ante organismos internacionales de regulación de inteligencia artificial. La compañía indicó que este tipo de monitoreo preventivo seguirá siendo una prioridad mientras la adopción de la IA continúe expandiéndose a nivel global.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-09-09" },
  { id: 2, categoria: "Tecnología", titulo: "Bill Gates también reniega de la inteligencia artificial", resumen: "Hace unos años, plantear que alguien como Bill Gates pudiera pedir freno a la inteligencia artificial habría sonado a contradicción.", contenido: "El cofundador de Microsoft, uno de los mayores impulsores de la digitalización mundial, expresó públicamente su preocupación por el ritmo acelerado con el que se están desplegando los sistemas de inteligencia artificial sin marcos regulatorios claros. Gates hizo un llamado a la industria tecnológica para priorizar la seguridad y la transparencia por encima de la velocidad de innovación, y sugirió la creación de estándares internacionales que permitan auditar el comportamiento de los modelos antes de su lanzamiento masivo.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-09-05" },
  { id: 3, categoria: "Educación", titulo: "Rector de la UNAM pide a los estudiantes usar el pensamiento crítico ante la tecnología digital", resumen: "Leonardo Lomelí Vanegas hizo tal solicitud para que los jóvenes generen un conocimiento confiable e integral.", contenido: "Durante la inauguración del semestre académico, el rector de la Universidad Nacional Autónoma de México invitó a la comunidad estudiantil a no depender exclusivamente de las herramientas de inteligencia artificial para la elaboración de trabajos académicos. Señaló que el pensamiento crítico y la verificación de fuentes deben seguir siendo la base de la formación universitaria, incluso en un contexto donde la tecnología facilita el acceso a la información.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-08-28" },
  { id: 4, categoria: "Tecnología", titulo: "¿Con cuántos salarios mínimos se puede comprar el iPhone Duo? Vea los precios oficiales del iPhone 18 Pro Max", resumen: "Se proyectó un aumento de 100 dólares, equivalente a unos $312.000 pesos colombianos según la TRM.", contenido: "El 9 de septiembre, en el Apple Event 2026, se dieron a conocer los nuevos aparatos electrónicos de la empresa, entre ellos el iPhone 18 y el novedoso iPhone Duo plegable. La preventa de los nuevos modelos inicia el sábado 12 de septiembre y llegan a tiendas a partir del 19 de septiembre. Según la información compartida en el evento, los modelos vendrían con diferentes precios según su categoría y capacidad de almacenamiento.", imagen: "img/Imagen-Prueba.png", autor: "Álvaro Richard Ruiz Martínez", fecha: "2026-09-09" },
  { id: 5, categoria: "Educación", titulo: "ICETEX ofrece descuento en la matrícula para estudiar en Reino Unido: así puede aplicar", resumen: "Convocatoria de becas de descuento académico gestionada por el ICETEX en alianza con la Universidad de Salford, Reino Unido, para estudios de maestría presenciales.", contenido: "El Instituto Colombiano de Crédito Educativo y Estudios Técnicos en el Exterior (ICETEX) abrió una nueva convocatoria en alianza con la Universidad de Salford, que ofrece un descuento significativo en el valor de la matrícula para programas de maestría presenciales. Los interesados deben cumplir con los requisitos académicos y de idioma establecidos, además de completar el proceso de postulación a través de la plataforma oficial del ICETEX antes de la fecha límite.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-09-02" },
  { id: 6, categoria: "Educación", titulo: "SENA ofrece 40.000 cupos en 1.500 programas presenciales y virtuales: ¿cómo inscribirse?", resumen: "Incluye programas de nivel Auxiliar, Operario, Técnico, Profundización Técnica y Tecnólogo en áreas como Construcción, Contabilidad, Sistemas, Recursos Humanos y Cocina.", contenido: "El Servicio Nacional de Aprendizaje (SENA) anunció la apertura de una nueva convocatoria con miles de cupos disponibles a nivel nacional, distribuidos en modalidades presencial y virtual. La oferta educativa cubre distintas áreas del conocimiento y busca fortalecer la formación técnica y tecnológica de los colombianos. Las inscripciones se realizan a través del portal oficial de la entidad y no tienen ningún costo para los aspirantes.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-08-30" },
  { id: 7, categoria: "Tecnología", titulo: "Anthropic alerta de que ha frenado posibles intentos de crear armas biológicas con su IA", resumen: "La compañía desconoce si la motivación detrás de estos accesos era la investigación científica o los usos maliciosos.", contenido: "El anuncio se produce después de que uno de sus ingenieros alertara del peligro existencial de estas herramientas si no se establecen controles adecuados. Anthropic detalló que reforzará sus sistemas de clasificación de contenido sensible y ampliará el equipo dedicado a la seguridad de sus modelos.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-09-10" },
  { id: 8, categoria: "Tecnología", titulo: "La inteligencia artificial avanza más rápido que las reglas para controlarla", resumen: "Informe preliminar presentado por el Panel Científico Internacional Independiente sobre Inteligencia Artificial de la ONU.", contenido: "El informe advierte que las capacidades de la inteligencia artificial avanzan mucho más rápido que la capacidad de los gobiernos para regularla, lo que genera vacíos normativos en materia de responsabilidad, transparencia y derechos humanos. El panel recomendó la creación de un organismo multilateral permanente que realice seguimiento continuo a los riesgos emergentes.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-09-01" },
  { id: 9, categoria: "Tecnología", titulo: "Apple presentó los AirPods 5 con mayor cancelación de ruido y nuevas funciones de IA", resumen: "La nueva generación de auriculares llega con mejoras de sonido, además de herramientas como Siri mediante gestos y traducción en tiempo real.", contenido: "Durante el mismo evento en el que se presentaron los nuevos modelos de iPhone, Apple aprovechó para renovar su línea de audífonos inalámbricos, incorporando un chip dedicado al procesamiento de inteligencia artificial en el dispositivo. Entre las novedades más destacadas se encuentran la traducción simultánea de conversaciones y el control mediante gestos de la cabeza.", imagen: "img/Imagen-Prueba.png", autor: "Redacción Infonexia", fecha: "2026-09-09" }
];

/* Une noticias base con las creadas por el usuario en localStorage. */
function obtenerTodasLasNoticias() {
  const creadas = JSON.parse(localStorage.getItem("infonexia_noticias_creadas") || "[]");
  return [...creadas, ...NOTICIAS_BASE];
}

function obtenerNoticiaPorId(id) {
  return obtenerTodasLasNoticias().find((n) => String(n.id) === String(id));
}

/* Alta: id con prefijo "u" para distinguirlas de las noticias base. */
function crearNoticia(noticia) {
  const creadas = JSON.parse(localStorage.getItem("infonexia_noticias_creadas") || "[]");
  const nuevoId = "u" + Date.now();
  creadas.unshift({ ...noticia, id: nuevoId, imagen: "img/Imagen-Prueba.png" });
  localStorage.setItem("infonexia_noticias_creadas", JSON.stringify(creadas));
}

/* Baja: solo afecta noticias creadas por el usuario. */
function eliminarNoticiaCreada(id) {
  const creadas = JSON.parse(localStorage.getItem("infonexia_noticias_creadas") || "[]");
  const filtradas = creadas.filter((n) => String(n.id) !== String(id));
  localStorage.setItem("infonexia_noticias_creadas", JSON.stringify(filtradas));
}
